#ifndef ERRORS_H
#define ERRORS_H
#define COMPILATION_FAILED 10
#define LINKING_FAILED 20
#define EVENTHANDLER_ALREADY_EXISTS 30
#define RENDERER_ALREADY_EXISTS 40
#define SHADER_FILE_NOT_FOUND 50
#endif //ERRORS_H