#ifndef ERRORS_H
#define ERRORS_H
#define COMPILATION_FAILED 10
#define LINKING_FAILED 20
#define EVENTHANDLER_ALREADY_SETUP 30
#define ALREDY_INITIALIZED 40
#define SHADER_FILE_NOT_FOUND 50
#define GLFW_ERROR 60
#endif //ERRORS_H